import fs from 'node:fs'

const file = 'src/App.tsx'
let source = fs.readFileSync(file, 'utf8')

const replaceOnce = (needle, replacement, label) => {
  if (!source.includes(needle)) throw new Error(`Missing target: ${label}`)
  source = source.replace(needle, replacement)
}

replaceOnce(
  "const trackingIndex = (status: string) => status === 'Processing' ? 0 : status === 'Accepted' ? 2 : status === 'Shipped' ? 3 : 4\n",
  "const trackingIndex = (status: string) => status === 'Processing' ? 0 : status === 'Accepted' ? 2 : status === 'Shipped' ? 3 : 4\nconst API_BASE = import.meta.env.DEV ? 'http://localhost:10000/api' : '/.netlify/functions/api'\nconst getApiToken = () => localStorage.getItem('apna_cart_api_token') || ''\nconst getSavedApiUser = (): UserProfile | null => {\n  try { return JSON.parse(localStorage.getItem('apna_cart_api_user') || 'null') as UserProfile | null } catch { return null }\n}\n",
  'API helpers',
)

replaceOnce(
  "  const [confirmationResult, setConfirmationResult] = useState<ConfirmationResult | null>(null)\n",
  "  const [confirmationResult, setConfirmationResult] = useState<ConfirmationResult | null>(null)\n  const [authMode, setAuthMode] = useState<'backend' | 'firebase'>('backend')\n",
  'auth mode state',
)

replaceOnce(
  "  useEffect(() => {\n    if (!auth || !db || !firebaseConfigured) return\n",
  "  useEffect(() => {\n    const token = getApiToken()\n    const savedUser = getSavedApiUser()\n    if (!token || !savedUser) return\n    setAuthMode('backend')\n    setUser(savedUser)\n    fetch(`${API_BASE}/orders`, { headers: { Authorization: `Bearer ${token}` } })\n      .then(async (response) => {\n        if (!response.ok) throw new Error('Backend session expired.')\n        return response.json()\n      })\n      .then((orders) => {\n        const history = orders.flatMap((order: any) => order.items.map((item: Product & { quantity: number }) => ({ ...item, status: order.status, location: order.location, phone: order.customer?.phone || order.customer?.contact || '', email: order.customer?.email || '', orderId: String(order.id) })))\n        setOrderHistory(history)\n      })\n      .catch(() => { localStorage.removeItem('apna_cart_api_token'); localStorage.removeItem('apna_cart_api_user'); setUser(null) })\n  }, [])\n\n  useEffect(() => {\n    if (getApiToken()) return\n    if (!auth || !db || !firebaseConfigured) return\n",
  'backend session restore',
)

const oldRequest = `  const requestOtp = async (event: React.FormEvent<HTMLFormElement>) => {\n    event.preventDefault()\n    try {\n      const { auth: firebaseAuth } = requireFirebase()\n      if (!recaptchaVerifier.current) recaptchaVerifier.current = new RecaptchaVerifier(firebaseAuth, 'recaptcha-container', { size: 'invisible' })\n      const confirmation = await signInWithPhoneNumber(firebaseAuth, loginContact.trim(), recaptchaVerifier.current)\n      setConfirmationResult(confirmation)\n      setLoginStep('otp')\n      setSmsNotice(\`OTP sent to \${loginContact}.\`)\n    } catch (error) {\n      recaptchaVerifier.current?.clear()\n      recaptchaVerifier.current = null\n      setSmsNotice(error instanceof Error ? error.message : 'OTP could not be sent.')\n    }\n  }`
const newRequest = `  const requestOtp = async (event: React.FormEvent<HTMLFormElement>) => {\n    event.preventDefault()\n    try {\n      const backendResponse = await fetch(\`${'${API_BASE}'}/auth/request-otp\`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: loginName.trim(), contact: loginContact.trim() }) })\n      if (backendResponse.ok) {\n        setAuthMode('backend')\n        setLoginStep('otp')\n        setSmsNotice(\`OTP sent to \${loginContact}.\`)\n        return\n      }\n      const backendMessage = await backendResponse.json().catch(() => ({}))\n      if (!firebaseConfigured) throw new Error(backendMessage.message || 'OTP provider is not configured.')\n      setAuthMode('firebase')\n      const { auth: firebaseAuth } = requireFirebase()\n      if (!recaptchaVerifier.current) recaptchaVerifier.current = new RecaptchaVerifier(firebaseAuth, 'recaptcha-container', { size: 'invisible' })\n      const confirmation = await signInWithPhoneNumber(firebaseAuth, loginContact.trim(), recaptchaVerifier.current)\n      setConfirmationResult(confirmation)\n      setLoginStep('otp')\n      setSmsNotice(\`OTP sent to \${loginContact}.\`)\n    } catch (error) {\n      recaptchaVerifier.current?.clear()\n      recaptchaVerifier.current = null\n      setSmsNotice(error instanceof Error ? error.message : 'OTP could not be sent.')\n    }\n  }`
replaceOnce(oldRequest, newRequest, 'requestOtp')

const oldVerify = `  const verifyOtp = async (event: React.FormEvent<HTMLFormElement>) => {\n    event.preventDefault()\n    try {\n      if (!confirmationResult) throw new Error('Please request an OTP first.')\n      const result = await confirmationResult.confirm(loginOtp.trim())\n      const { db: firestoreDb } = requireFirebase()\n      await setDoc(doc(firestoreDb, 'users', result.user.uid), { uid: result.user.uid, phoneNumber: result.user.phoneNumber || loginContact.trim(), name: loginName.trim() || 'Apna Cart shopper', email: result.user.email || '', address: customerAddress, updatedAt: serverTimestamp() }, { merge: true })\n      setUser({ name: loginName.trim() || 'Apna Cart shopper', contact: result.user.phoneNumber || loginContact.trim() })\n      setLoginOpen(false)\n      setConfirmationResult(null)\n      setSmsNotice('Login successful. You can now place your order.')\n      if (cart.length > 0) setCheckoutOpen(true)\n    } catch (error) { setSmsNotice(error instanceof Error ? error.message : 'OTP verification failed.') }\n  }`
const newVerify = `  const verifyOtp = async (event: React.FormEvent<HTMLFormElement>) => {\n    event.preventDefault()\n    try {\n      if (authMode === 'backend') {\n        const response = await fetch(\`${'${API_BASE}'}/auth/verify-otp\`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contact: loginContact.trim(), otp: loginOtp.trim() }) })\n        const data = await response.json().catch(() => ({}))\n        if (!response.ok) throw new Error(data.message || 'OTP verification failed.')\n        const apiUser = data.user as UserProfile\n        localStorage.setItem('apna_cart_api_token', data.token)\n        localStorage.setItem('apna_cart_api_user', JSON.stringify(apiUser))\n        setUser(apiUser)\n        setLoginOpen(false)\n        setSmsNotice('Login successful. You can now place your order.')\n        const ordersResponse = await fetch(\`${'${API_BASE}'}/orders\`, { headers: { Authorization: `Bearer ${data.token}` } })\n        if (ordersResponse.ok) {\n          const orders = await ordersResponse.json()\n          setOrderHistory(orders.flatMap((order: any) => order.items.map((item: Product & { quantity: number }) => ({ ...item, status: order.status, location: order.location, phone: order.customer?.phone || order.customer?.contact || '', email: order.customer?.email || '', orderId: String(order.id) }))))\n        }\n        if (cart.length > 0) setCheckoutOpen(true)\n        return\n      }\n      if (!confirmationResult) throw new Error('Please request an OTP first.')\n      const result = await confirmationResult.confirm(loginOtp.trim())\n      const { db: firestoreDb } = requireFirebase()\n      await setDoc(doc(firestoreDb, 'users', result.user.uid), { uid: result.user.uid, phoneNumber: result.user.phoneNumber || loginContact.trim(), name: loginName.trim() || 'Apna Cart shopper', email: result.user.email || '', address: customerAddress, updatedAt: serverTimestamp() }, { merge: true })\n      setUser({ name: loginName.trim() || 'Apna Cart shopper', contact: result.user.phoneNumber || loginContact.trim() })\n      setLoginOpen(false)\n      setConfirmationResult(null)\n      setSmsNotice('Login successful. You can now place your order.')\n      if (cart.length > 0) setCheckoutOpen(true)\n    } catch (error) { setSmsNotice(error instanceof Error ? error.message : 'OTP verification failed.') }\n  }`
replaceOnce(oldVerify, newVerify, 'verifyOtp')

const oldPlaceStart = `  const placeOrder = async (event: React.FormEvent<HTMLFormElement>) => {\n    event.preventDefault()\n    if (!user || !firebaseUser) { openLogin(); return }\n    try {\n      const { db: firestoreDb } = requireFirebase()`
const newPlaceStart = `  const placeOrder = async (event: React.FormEvent<HTMLFormElement>) => {\n    event.preventDefault()\n    if (!user) { openLogin(); return }\n    const apiToken = getApiToken()\n    if (apiToken) {\n      try {\n        const response = await fetch(\`${'${API_BASE}'}/orders\`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiToken}` }, body: JSON.stringify({ items: cartItems.map(({ product, quantity }) => ({ ...product, quantity })), total: cartTotal, paymentMethod, address: customerAddress, phone: customerPhone, email: customerEmail }) })\n        const data = await response.json().catch(() => ({}))\n        if (!response.ok) throw new Error(data.message || 'Order could not be placed.')\n        const order = data.order\n        setOrderHistory((orders) => [...order.items.map((item: Product & { quantity: number }) => ({ ...item, status: order.status, location: order.location, phone: order.customer.phone, email: order.customer.email, orderId: String(order.id) })), ...orders])\n        setCart([])\n        setCheckoutOpen(false)\n        setOrdersOpen(true)\n        setSmsNotice(\`Thanks \${customerName || user.name}! Your order is confirmed.\`)\n        return\n      } catch (error) { setSmsNotice(error instanceof Error ? error.message : 'Order could not be placed.'); return }\n    }\n    try {\n      const { db: firestoreDb } = requireFirebase()`
replaceOnce(oldPlaceStart, newPlaceStart, 'placeOrder start')

const oldUpdate = `  const updateOrderStatus = async (order: OrderItem, index: number, status: string, location: string) => {\n    try {\n      const { db: firestoreDb } = requireFirebase()\n      if (order.orderId) await updateDoc(doc(firestoreDb, 'orders', order.orderId), { status, location })\n      setOrderHistory((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, status, location } : item))\n    } catch (error) { setSmsNotice(error instanceof Error ? error.message : 'Order status could not be updated.') }\n  }`
const newUpdate = `  const updateOrderStatus = async (order: OrderItem, index: number, status: string, location: string) => {\n    try {\n      const apiToken = getApiToken()\n      if (apiToken && order.orderId) {\n        const response = await fetch(\`${'${API_BASE}'}/orders/\${order.orderId}/status\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiToken}` }, body: JSON.stringify({ status, location }) })\n        const data = await response.json().catch(() => ({}))\n        if (!response.ok) throw new Error(data.message || 'Order status could not be updated.')\n      } else if (order.orderId) {\n        const { db: firestoreDb } = requireFirebase()\n        await updateDoc(doc(firestoreDb, 'orders', order.orderId), { status, location })\n      }\n      setOrderHistory((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, status, location } : item))\n    } catch (error) { setSmsNotice(error instanceof Error ? error.message : 'Order status could not be updated.') }\n  }`
replaceOnce(oldUpdate, newUpdate, 'updateOrderStatus')

replaceOnce(
  "onClick={async () => { if (auth) await signOut(auth); setUser(null); setProfileOpen(false); setSmsNotice('You have been logged out.') }}",
  "onClick={async () => { if (auth) await signOut(auth); localStorage.removeItem('apna_cart_api_token'); localStorage.removeItem('apna_cart_api_user'); setUser(null); setOrderHistory([]); setProfileOpen(false); setSmsNotice('You have been logged out.') }}",
  'logout',
)

fs.writeFileSync(file, source)
console.log('Backend API integration applied to src/App.tsx')
