import { useEffect, useMemo, useState } from 'react'
import { signInWithEmailAndPassword, signOut } from 'firebase/auth'
import { auth } from './firebase'
import './admin-panel.css'

type Product={id:number|string;name?:string;price?:number;oldPrice?:number;category?:string;gender?:string;stock?:number;image?:string;description?:string}
type Order={id?:string|number;total?:number;status?:string;contact?:string;phone?:string;createdAt?:string}
type Tab='dashboard'|'products'|'orders'|'customers'|'earnings'|'sellers'
const API_BASE=import.meta.env.DEV?'http://localhost:10000/api':'https://apna-cart-2rcq.onrender.com/api'
const emptyProduct={name:'',price:'',oldPrice:'',category:'All Categories',gender:'Unisex',stock:'0',image:'',description:''}

export default function AdminPanel(){
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[loggedIn,setLoggedIn]=useState(Boolean(auth?.currentUser));const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[products,setProducts]=useState<Product[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[refreshing,setRefreshing]=useState(false);const[tab,setTab]=useState<Tab>('dashboard');const[form,setForm]=useState(emptyProduct);const[editing,setEditing]=useState<Product|null>(null);const[saving,setSaving]=useState(false)
 const api=async(path:string,options:RequestInit={})=>{const token=auth?.currentUser?await auth.currentUser.getIdToken():'';return fetch(`${API_BASE}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}})}
 const loadData=async()=>{setRefreshing(true);setError('');try{const[pr,or]=await Promise.all([api('/products'),api('/orders')]);const pd=await pr.json().catch(()=>({}));const od=await or.json().catch(()=>({}));if(!pr.ok)throw new Error(pd?.error||'Products load failed');setProducts(Array.isArray(pd?.products)?pd.products:[]);setOrders(Array.isArray(od?.orders)?od.orders:[])}catch(e){setError(e instanceof Error?e.message:'Backend data load failed.')}finally{setRefreshing(false)}}
 useEffect(()=>{if(loggedIn)loadData()},[loggedIn])
 const revenue=useMemo(()=>orders.reduce((s,o)=>s+Number(o.total||0),0),[orders]);const deliveredRevenue=useMemo(()=>orders.filter(o=>['delivered','completed'].includes(String(o.status||'').toLowerCase())).reduce((s,o)=>s+Number(o.total||0),0),[orders]);const pending=useMemo(()=>orders.filter(o=>!['delivered','cancelled','completed'].includes(String(o.status||'').toLowerCase())).length,[orders]);const cancelled=useMemo(()=>orders.filter(o=>String(o.status||'').toLowerCase()==='cancelled').length,[orders]);const avgOrder=orders.length?revenue/orders.length:0
 const customers=useMemo(()=>{const map=new Map<string,{contact:string;orders:number;spent:number;lastOrder?:string}>();orders.forEach(o=>{const contact=String(o.contact||o.phone||'Unknown');const old=map.get(contact)||{contact,orders:0,spent:0};old.orders+=1;old.spent+=Number(o.total||0);if(o.createdAt)old.lastOrder=o.createdAt;map.set(contact,old)});return [...map.values()].sort((a,b)=>b.spent-a.spent)},[orders])
 const login=async(e:React.FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{if(!auth)throw new Error('Firebase is not configured in this deployment.');const c=await signInWithEmailAndPassword(auth,email.trim(),password);const allowed=String(import.meta.env.VITE_ADMIN_EMAIL||'').trim().toLowerCase();if(allowed&&c.user.email?.toLowerCase()!==allowed){await signOut(auth);throw new Error('This account is not an authorised Apna Cart owner account.')}setLoggedIn(true);setPassword('')}catch(e){setError(e instanceof Error?e.message:'Admin login failed.')}finally{setLoading(false)}}
 const logout=async()=>{if(auth)await signOut(auth);setLoggedIn(false);setProducts([]);setOrders([])}
 const startEdit=(p:Product)=>{setEditing(p);setForm({name:p.name||'',price:String(p.price??''),oldPrice:String(p.oldPrice??p.price??''),category:p.category||'All Categories',gender:p.gender||'Unisex',stock:String(p.stock??0),image:p.image||'',description:p.description||''});setTab('products');window.scrollTo({top:0,behavior:'smooth'})}
 const saveProduct=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');const payload={name:form.name.trim(),price:Number(form.price),oldPrice:Number(form.oldPrice||form.price),category:form.category,gender:form.gender,stock:Number(form.stock||0),image:form.image.trim(),description:form.description.trim()};try{if(!payload.name||!payload.price)throw new Error('Product name aur price required hai.');const r=editing?await api(`/products/${encodeURIComponent(String(editing.id))}`,{method:'PUT',body:JSON.stringify(payload)}):await api('/products',{method:'POST',body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`Product save failed (${r.status})`);setForm(emptyProduct);setEditing(null);await loadData()}catch(e){setError(e instanceof Error?e.message:'Product save failed.')}finally{setSaving(false)}}
 const deleteProduct=async(p:Product)=>{if(!confirm(`Delete ${p.name||'this product'}?`))return;setError('');try{const r=await api(`/products/${encodeURIComponent(String(p.id))}`,{method:'DELETE'});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d?.error||`Delete failed (${r.status})`)}await loadData()}catch(e){setError(e instanceof Error?e.message:'Delete failed.')}}
 const updateOrder=async(o:Order,status:string)=>{setError('');try{const r=await api(`/orders/${encodeURIComponent(String(o.id))}`,{method:'PUT',body:JSON.stringify({status})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d?.error||`Order update failed (${r.status})`)}await loadData()}catch(e){setError(e instanceof Error?e.message:'Order update failed.')}}
 if(!loggedIn)return <main className="admin-shell admin-login-page"><section className="admin-login-card"><div className="admin-logo">🛍️</div><h1>Apna Cart Owner Panel</h1><p>Sirf authorised owner account se login karein.</p><form onSubmit={login}><label>Email<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Owner email" required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/></label>{error&&<div className="admin-error">{error}</div>}<button className="admin-primary" disabled={loading}>{loading?'Logging in…':'Owner Login'}</button></form><button className="admin-back" onClick={()=>{window.location.href='/'}}>← Back to Apna Cart</button></section></main>
 return <main className="admin-shell"><header className="admin-topbar"><div><div className="admin-kicker">APNA CART</div><h1>Owner / Admin Panel</h1></div><div className="admin-actions"><button onClick={loadData} disabled={refreshing}>{refreshing?'Refreshing…':'↻ Refresh'}</button><button onClick={logout}>Logout</button></div></header><div className="admin-layout"><aside className="admin-sidebar"><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>📊 Dashboard</button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>📦 Products</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>🧾 Orders</button><button className={tab==='sellers'?'active':''} onClick={()=>setTab('sellers')}>🏪 Sellers</button><button className={tab==='customers'?'active':''} onClick={()=>setTab('customers')}>👥 Customers</button><button className={tab==='earnings'?'active':''} onClick={()=>setTab('earnings')}>💰 Earnings</button></aside><section className="admin-content">{error&&<div className="admin-error" style={{marginBottom:16}}>{error}</div>}
 {tab==='dashboard'&&<><div className="admin-cards"><article><span>Total Products</span><strong>{products.length}</strong></article><article><span>Total Orders</span><strong>{orders.length}</strong></article><article><span>Pending Orders</span><strong>{pending}</strong></article><article><span>Order Value</span><strong>₹{revenue.toLocaleString('en-IN')}</strong></article></div><div className="admin-grid"><section className="admin-panel-card"><h2>Recent Orders</h2>{orders.length===0?<p className="muted">Abhi order data nahi mila.</p>:<div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.slice(0,8).map((o,i)=><tr key={String(o.id??i)}><td>#{o.id??i+1}</td><td>₹{Number(o.total||0).toLocaleString('en-IN')}</td><td><span className="status">{o.status||'pending'}</span></td></tr>)}</tbody></table></div>}</section><section className="admin-panel-card"><h2>Owner Controls</h2><div className="control-list"><div>🔐 <b>Protected login</b><small>Firebase owner authentication</small></div><div>📦 <b>Product management</b><small>Add, edit, stock and delete products</small></div><div>🧾 <b>Order management</b><small>Open orders and change status</small></div><div>📈 <b>Reports</b><small>Customer and earnings summaries from live order data</small></div></div></section></div></>}
 {tab==='products'&&<><section className="admin-panel-card"><h2>{editing?'Edit Product':'Add New Product'}</h2><form onSubmit={saveProduct} className="admin-product-form"><input placeholder="Product name *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input type="number" min="0" placeholder="Selling price *" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/><input type="number" min="0" placeholder="Old price" value={form.oldPrice} onChange={e=>setForm({...form,oldPrice:e.target.value})}/><input type="number" min="0" placeholder="Stock" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="Gender" value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}/><input placeholder="Image URL" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="admin-form-actions"><button className="admin-primary" disabled={saving}>{saving?'Saving…':editing?'Update Product':'Add Product'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(emptyProduct)}}>Cancel</button>}</div></form></section><section className="admin-panel-card" style={{marginTop:18}}><h2>Products ({products.length})</h2><div className="admin-table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Category</th><th>Action</th></tr></thead><tbody>{products.map((p,i)=><tr key={String(p.id??i)}><td>{p.name||'Unnamed'}</td><td>₹{Number(p.price||0).toLocaleString('en-IN')}</td><td>{p.stock??'—'}</td><td>{p.category||'—'}</td><td><button onClick={()=>startEdit(p)}>Edit</button> <button onClick={()=>deleteProduct(p)}>Delete</button></td></tr>)}</tbody></table></div></section></>}
 {tab==='orders'&&<section className="admin-panel-card"><h2>Order Management ({orders.length})</h2>{orders.length===0?<p className="muted">Abhi order data nahi mila.</p>:<div className="admin-table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Amount</th><th>Status</th><th>Change</th></tr></thead><tbody>{orders.map((o,i)=><tr key={String(o.id??i)}><td>#{o.id??i+1}</td><td>{o.contact||o.phone||'—'}</td><td>₹{Number(o.total||0).toLocaleString('en-IN')}</td><td><span className="status">{o.status||'pending'}</span></td><td><select value={o.status||'pending'} onChange={e=>updateOrder(o,e.target.value)}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></td></tr>)}</tbody></table></div>}</section>}
 {tab==='customers'&&<section className="admin-panel-card"><h2>Customers ({customers.length})</h2><p className="muted">Customer list live orders se derive ki gayi hai.</p>{customers.length===0?<p className="muted">Abhi customer data nahi mila.</p>:<div className="admin-table-wrap"><table><thead><tr><th>Contact</th><th>Orders</th><th>Total Spent</th><th>Last Order</th></tr></thead><tbody>{customers.map(c=><tr key={c.contact}><td>{c.contact}</td><td>{c.orders}</td><td>₹{c.spent.toLocaleString('en-IN')}</td><td>{c.lastOrder?new Date(c.lastOrder).toLocaleString('en-IN'):'—'}</td></tr>)}</tbody></table></div>}</section>}
 {tab==='earnings'&&<><div className="admin-cards"><article><span>Gross Order Value</span><strong>₹{revenue.toLocaleString('en-IN')}</strong></article><article><span>Delivered Revenue</span><strong>₹{deliveredRevenue.toLocaleString('en-IN')}</strong></article><article><span>Average Order</span><strong>₹{Math.round(avgOrder).toLocaleString('en-IN')}</strong></article><article><span>Cancelled Orders</span><strong>{cancelled}</strong></article></div><section className="admin-panel-card" style={{marginTop:18}}><h2>Earnings / Reports</h2><p className="muted">Ye report current order records par based hai. Isme gross order value, delivered revenue aur average order value dikhaya gaya hai.</p><div className="admin-table-wrap"><table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody><tr><td>All orders value</td><td>₹{revenue.toLocaleString('en-IN')}</td></tr><tr><td>Delivered/completed value</td><td>₹{deliveredRevenue.toLocaleString('en-IN')}</td></tr><tr><td>Pending orders</td><td>{pending}</td></tr><tr><td>Cancelled orders</td><td>{cancelled}</td></tr><tr><td>Customers with orders</td><td>{customers.length}</td></tr></tbody></table></div></section></>}
 {tab==='sellers'&&<section className="admin-panel-card"><h2>Seller Management</h2><p>Seller registration backend already uses the <b>sellers</b> collection. fileciteturn55file0</p><p className="muted">Is admin view mein seller approval/list endpoint abhi backend mein available nahi mila, isliye yahan fake seller data nahi dikhaya gaya.</p><div className="control-list"><div>🏪 <b>Seller registration</b><small>Seller accounts are stored in Firebase when backend is configured.</small></div><div>⚠️ <b>Next backend step</b><small>Owner-only seller list, approve/reject and seller status APIs add karne hain.</small></div></div></section>}
 </section></div></main>
}
