import { useEffect, useMemo, useState } from 'react'

type Product = { id: number; name: string; category: string; gender?: string; price: number; oldPrice: number; image: string; rating: number; reviews: number; discount: string; description: string }
type CartLine = { productId: number; quantity: number }
type User = { name: string; contact: string }
type Order = { id: string | number; items: Array<Product & { quantity: number }>; total: number; status: string; location: string; phone: string; email: string; address?: string }
type PaymentMethod = 'UPI' | 'Card' | 'Net banking' | 'Wallet' | 'Cash on Delivery'

const API_BASE = import.meta.env.DEV ? 'http://localhost:10000/api' : 'https://apna-cart-2rcq.onrender.com/api'

const products: Product[] = [
  { id: 1, name: 'Festive Kurti Set', category: '8PM Offer', gender: 'Women', price: 399, oldPrice: 799, image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 120, discount: '50% OFF', description: 'Soft and comfortable ethnic kurti set for festive and everyday wear.' },
  { id: 2, name: 'Men Casual T-Shirt Combo', category: '8PM Offer', gender: 'Men', price: 499, oldPrice: 999, image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 98, discount: '50% OFF', description: 'Comfortable cotton T-shirt combo suitable for daily casual wear.' },
  { id: 3, name: 'Printed Silk Saree', category: 'Saree', gender: 'Women', price: 699, oldPrice: 1499, image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 156, discount: '53% OFF', description: 'Elegant printed saree with a graceful finish for parties and functions.' },
  { id: 4, name: 'Embroidered Party Saree', category: 'Saree', gender: 'Women', price: 899, oldPrice: 1899, image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 74, discount: '53% OFF', description: 'Stylish embroidered saree designed for festive and special occasions.' },
  { id: 5, name: 'Women Western Top', category: 'Western Wear', gender: 'Women', price: 349, oldPrice: 699, image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 112, discount: '50% OFF', description: 'Trendy lightweight western top with a comfortable everyday fit.' },
  { id: 6, name: 'Women Casual Dress', category: 'Western Wear', gender: 'Women', price: 599, oldPrice: 1199, image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 89, discount: '50% OFF', description: 'Modern casual dress with a flattering fit for outings and everyday style.' },
  { id: 7, name: 'Artificial Necklace Set', category: 'Jewellery', gender: 'Women', price: 299, oldPrice: 699, image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=85', rating: 4.2, reviews: 61, discount: '57% OFF', description: 'Elegant imitation jewellery set that adds a festive touch to your look.' },
  { id: 8, name: 'Gold Tone Earrings', category: 'Jewellery', gender: 'Women', price: 199, oldPrice: 499, image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 83, discount: '60% OFF', description: 'Lightweight gold-tone earrings for daily wear and special occasions.' },
  { id: 9, name: "Men's Casual Shirt", category: 'Men', gender: 'Men', price: 449, oldPrice: 899, image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 130, discount: '50% OFF', description: 'Regular-fit casual shirt made for comfortable everyday styling.' },
  { id: 10, name: "Men's Sports Watch", category: 'Men', gender: 'Men', price: 799, oldPrice: 1799, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 92, discount: '56% OFF', description: 'Sporty everyday watch with a clean dial and durable strap.' },
  { id: 11, name: 'Non-Stick Cookware Set', category: 'Kitchen', gender: 'Unisex', price: 999, oldPrice: 1999, image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 72, discount: '50% OFF', description: 'Useful non-stick cookware set for everyday home cooking.' },
  { id: 12, name: 'Stainless Steel Pan Set', category: 'Kitchen', gender: 'Unisex', price: 649, oldPrice: 1299, image: 'https://images.unsplash.com/photo-1584990347449-ae2c3b5f2b19?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 48, discount: '50% OFF', description: 'Durable stainless-steel kitchen pan set for regular cooking needs.' },
  { id: 13, name: 'Printed Cotton Kurti', category: 'Kurtis & Dresses', gender: 'Women', price: 399, oldPrice: 799, image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=85', rating: 4.6, reviews: 145, discount: '50% OFF', description: 'Breathable cotton kurti with a comfortable fit for everyday use.' },
  { id: 14, name: 'Flared Ethnic Dress', category: 'Kurtis & Dresses', gender: 'Women', price: 649, oldPrice: 1299, image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 67, discount: '50% OFF', description: 'Beautiful flared ethnic dress for festive days and family occasions.' },
  { id: 15, name: 'Kids Printed T-Shirt', category: 'Kids', gender: 'Kids', price: 249, oldPrice: 499, image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 52, discount: '50% OFF', description: 'Soft printed T-shirt for active kids.' },
  { id: 16, name: 'Kids Party Dress', category: 'Kids', gender: 'Kids', price: 549, oldPrice: 1099, image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 46, discount: '50% OFF', description: 'Comfortable party dress for children.' },
  { id: 17, name: 'Indoor Money Plant', category: 'Home', gender: 'Unisex', price: 199, oldPrice: 399, image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 88, discount: '50% OFF', description: 'Easy-care indoor plant for home and office.' },
  { id: 18, name: 'Decorative Cushion Cover', category: 'Home', gender: 'Unisex', price: 179, oldPrice: 399, image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 43, discount: '55% OFF', description: 'Decorative cushion cover for a fresh home look.' },
  { id: 19, name: 'Matte Lipstick', category: 'Beauty', gender: 'Women', price: 199, oldPrice: 399, image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 104, discount: '50% OFF', description: 'Long-lasting matte lipstick with a comfortable finish.' },
  { id: 20, name: 'Beauty Makeup Kit', category: 'Beauty', gender: 'Women', price: 499, oldPrice: 999, image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 78, discount: '50% OFF', description: 'Everyday makeup essentials in one convenient kit.' },
  { id: 21, name: 'Running Shoes', category: 'Footwear', gender: 'Unisex', price: 699, oldPrice: 1399, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 118, discount: '50% OFF', description: 'Lightweight running shoes for daily activity.' },
  { id: 22, name: 'Casual Sneakers', category: 'Footwear', gender: 'Unisex', price: 799, oldPrice: 1599, image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 95, discount: '50% OFF', description: 'Comfortable casual sneakers for everyday wear.' },
  { id: 23, name: 'Wireless Headphones', category: 'All Categories', gender: 'Unisex', price: 899, oldPrice: 1799, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d3?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 65, discount: '48% OFF', description: 'Wireless headphones with comfortable ear cups for music and calls.' },
  { id: 24, name: 'Smartphone', category: 'All Categories', gender: 'Unisex', price: 12999, oldPrice: 18999, image: 'https://images.unsplash.com/photo-1511707171637-5f897ff02aa9?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 110, discount: '32% OFF', description: 'Modern smartphone suitable for everyday communication, apps and entertainment.' },
]

const categories: Array<[string,string]> = [['All Categories','▦'],['8PM Offer','🎁'],['Saree','👗'],['Western Wear','👚'],['Jewellery','💎'],['Men','👕'],['Kitchen','🍳'],['Kurtis & Dresses','🧥'],['Kids','🧸'],['Home','🏠'],['Beauty','💄'],['Footwear','👟']]
const money = (value: number) => `₹${value.toLocaleString('en-IN')}`
const genderFor = (p: Product) => p.gender || (p.category === 'Men' || /\bmen'?s?\b/i.test(p.name) ? 'Men' : p.category === 'Kids' || /\bkids?\b/i.test(p.name) ? 'Kids' : p.category === 'All Categories' && /smartphone|headphones/i.test(p.name) ? 'Unisex' : 'Women')

export default function App() {
  const [user,setUser]=useState<User|null>(()=>JSON.parse(localStorage.getItem('apna-cart-user')||'null'))
  const [cart,setCart]=useState<CartLine[]>(()=>JSON.parse(localStorage.getItem('apna-cart-cart')||'[]'))
  const [orders,setOrders]=useState<Order[]>([]); const [search,setSearch]=useState(''); const [category,setCategory]=useState('All'); const [gender,setGender]=useState('All'); const [sortBy,setSortBy]=useState('relevance'); const [view,setView]=useState('home'); const [selected,setSelected]=useState<Product|null>(null); const [loginOpen,setLoginOpen]=useState(false); const [address,setAddress]=useState(''); const [phone,setPhone]=useState(''); const [payment,setPayment]=useState<PaymentMethod>('Cash on Delivery'); const [message,setMessage]=useState(''); const [menuOpen,setMenuOpen]=useState(false)
  useEffect(()=>localStorage.setItem('apna-cart-cart',JSON.stringify(cart)),[cart]); useEffect(()=>{user?localStorage.setItem('apna-cart-user',JSON.stringify(user)):localStorage.removeItem('apna-cart-user')},[user]); useEffect(()=>{if(user) loadOrders()},[user])
  const loadOrders=async()=>{try{const r=await fetch(`${API_BASE}/orders?contact=${encodeURIComponent(user?.contact||'')}`);const d=await r.json();if(r.ok)setOrders(d.orders||[])}catch{}}
  const filtered=useMemo(()=>{let list=products.filter(p=>(category==='All'||p.category===category)||(category==='All Categories')); if(gender!=='All')list=list.filter(p=>genderFor(p)===gender); if(search.trim()){const q=search.toLowerCase();list=list.filter(p=>`${p.name} ${p.category} ${genderFor(p)} ${p.description} ${p.id}`.toLowerCase().includes(q))} if(sortBy==='price-low')list=[...list].sort((a,b)=>a.price-b.price); if(sortBy==='price-high')list=[...list].sort((a,b)=>b.price-a.price); if(sortBy==='rating')list=[...list].sort((a,b)=>b.rating-a.rating); return list},[category,gender,search,sortBy])
  const addToCart=(p:Product)=>{setCart(c=>{const old=c.find(x=>x.productId===p.id);return old?c.map(x=>x.productId===p.id?{...x,quantity:x.quantity+1}:x):[...c,{productId:p.id,quantity:1}]});setMessage(`${p.name} cart mein add ho gaya`);setTimeout(()=>setMessage(''),1800)}
  const cartCount=cart.reduce((s,x)=>s+x.quantity,0); const cartItems=cart.map(x=>({p:products.find(p=>p.id===x.productId)!,quantity:x.quantity})).filter(x=>x.p); const total=cartItems.reduce((s,x)=>s+x.p.price*x.quantity,0)
  const placeOrder=async()=>{if(!user){setLoginOpen(true);return} if(!address.trim()||!phone.trim()){setMessage('Address aur mobile number bhariye');return} try{const r=await fetch(`${API_BASE}/orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contact:user.contact,name:user.name,phone,address,paymentMethod:payment,items:cartItems.map(x=>({...x.p,quantity:x.quantity})),total})});const d=await r.json();if(!r.ok)throw Error(d.message||'Order failed');setOrders(o=>[d.order,...o]);setCart([]);setView('orders');setMessage('Order place ho gaya')}catch(e){setMessage(e instanceof Error?e.message:'Order failed')}}
  const home=()=>setView('home')
  return <div className="app-shell">
    <header className="header"><div className="header-topline"><button className="brand" onClick={home}>Apna Cart</button><div className="search-box"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by Keyword or Product ID"/><button aria-label="Voice search" type="button">🎙️</button><button aria-label="Camera search" type="button">📷</button></div><button className="cart-head" onClick={()=>setView('cart')}>🛒 <span>{cartCount}</span></button></div><div className="filter-row"><button onClick={()=>setMenuOpen(v=>!v)}>Categories ▾</button><button onClick={()=>setGender(g=>g==='All'?'Women':g==='Women'?'Men':g==='Men'?'Kids':'All')}>Gender: {gender} ▾</button><select value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="relevance">Sort: Relevance</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option><option value="rating">Top Rated</option></select></div>{menuOpen&&<div className="category-menu">{categories.map(([name,icon])=><button key={name} onClick={()=>{setCategory(name);setMenuOpen(false)}}>{icon} {name}</button>)}</div>}</header>
    <main>{view==='home'&&<><section className="hero-banner"><div><p>Apna Cart</p><h1>Best Quality<br/><b>Lowest Prices</b></h1><span>Fashion | Home | Beauty | More</span></div><button onClick={()=>setCategory('All')}>Shop Now</button></section><section className="category-strip">{categories.map(([name,icon])=><button key={name} onClick={()=>setCategory(name)}><span>{icon}</span>{name}</button>)}</section><section className="products-section"><div className="section-title"><h2>{search?`Results for “${search}”`:'Popular Products'}</h2><span>{filtered.length} items</span></div><div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id} onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><div className="product-info"><small>{genderFor(p)}</small><h3>{p.name}</h3><div><b>{money(p.price)}</b> <del>{money(p.oldPrice)}</del></div><div className="rating">★ {p.rating} ({p.reviews})</div><button onClick={e=>{e.stopPropagation();addToCart(p)}}>Add to Cart</button></div></article>)}</div></section></>}{view==='cart'&&<section className="page"><h2>Your Cart</h2>{cartItems.length===0?<p>Cart empty hai.</p>:<>{cartItems.map(x=><div className="cart-row" key={x.p.id}><img src={x.p.image} alt=""/><div><b>{x.p.name}</b><p>{money(x.p.price)} × {x.quantity}</p></div><button onClick={()=>setCart(c=>c.filter(y=>y.productId!==x.p.id))}>Remove</button></div>)}<h3>Total: {money(total)}</h3><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Delivery address"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Mobile number"/><select value={payment} onChange={e=>setPayment(e.target.value as PaymentMethod)}><option>Cash on Delivery</option><option>UPI</option><option>Card</option><option>Net banking</option><option>Wallet</option></select><button onClick={placeOrder}>Place Order</button></>}</section>}{view==='orders'&&<section className="page"><h2>My Orders</h2>{orders.length===0?<p>No orders yet.</p>:orders.map(o=><div className="order-card" key={String(o.id)}><b>Order #{o.id}</b><p>{o.status} · {money(o.total)}</p><p>{o.address||o.location||''}</p></div>)}</section>}</main>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="product-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt={selected.name}/><h2>{selected.name}</h2><p>{selected.description}</p><h3>{money(selected.price)}</h3><button onClick={()=>{addToCart(selected);setSelected(null)}}>Add to Cart</button></div></div>}
    {message&&<div className="toast">{message}</div>}
    <nav className="bottom-nav"><button onClick={home}>⌂<span>Home</span></button><button onClick={()=>setView('orders')}>▣<span>Orders</span></button><button onClick={()=>setView('cart')}>🛒<span>Cart</span></button><button onClick={()=>setLoginOpen(true)}>👤<span>Account</span></button></nav>
    {loginOpen&&<div className="modal-backdrop" onClick={()=>setLoginOpen(false)}><div className="login-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setLoginOpen(false)}>×</button><h2>Login / Register</h2><input placeholder="Name" id="login-name"/><input placeholder="Mobile / Email" id="login-contact"/><button onClick={()=>{const n=(document.getElementById('login-name') as HTMLInputElement)?.value.trim();const c=(document.getElementById('login-contact') as HTMLInputElement)?.value.trim();if(!n||!c){setMessage('Name aur mobile/email bhariye');return}setUser({name:n,contact:c});setLoginOpen(false);setMessage('Login ho gaya')}}>Continue</button></div></div>}
  </div>
}
