import { useEffect, useMemo, useState } from 'react'

type Product = { id: number; name: string; category: string; gender?: string; price: number; oldPrice: number; image: string; rating: number; reviews: number; discount: string; description: string }
type CartLine = { productId: number; quantity: number }
type User = { name: string; contact: string }
type Order = { id: string | number; items: Array<Product & { quantity: number }>; total: number; status: string; location: string; phone: string; email: string; address?: string }
type PaymentMethod = 'UPI' | 'Card' | 'Net banking' | 'Wallet' | 'Cash on Delivery'

const API_BASE = import.meta.env.DEV ? 'http://localhost:10000/api' : 'https://apna-cart-2rcq.onrender.com/api'

const products: Product[] = [
  { id: 1, name: 'Festive Kurti Set', category: '8PM Offer', gender: 'Women', price: 399, oldPrice: 799, image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 120, discount: '50% OFF', description: 'Soft and comfortable ethnic kurti set for festive and everyday wear.' },
  { id: 2, name: 'Men Casual T-Shirt Combo', category: '8PM Offer', gender: 'Men', price: 499, oldPrice: 999, image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 98, discount: '50% OFF', description: 'Comfortable cotton T-shirt combo suitable for daily casual wear.' },
  { id: 3, name: 'Printed Silk Saree', category: 'Saree', gender: 'Women', price: 699, oldPrice: 1499, image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 156, discount: '53% OFF', description: 'Elegant printed saree with a graceful finish for parties and functions.' },
  { id: 4, name: 'Embroidered Party Saree', category: 'Saree', gender: 'Women', price: 899, oldPrice: 1899, image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 74, discount: '53% OFF', description: 'Stylish embroidered saree designed for festive and special occasions.' },
  { id: 5, name: 'Women Western Top', category: 'Western Wear', gender: 'Women', price: 349, oldPrice: 699, image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 112, discount: '50% OFF', description: 'Trendy lightweight western top with a comfortable everyday fit.' },
  { id: 6, name: 'Women Casual Dress', category: 'Western Wear', gender: 'Women', price: 599, oldPrice: 1199, image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 89, discount: '50% OFF', description: 'Modern casual dress with a flattering fit for outings and everyday style.' },
  { id: 7, name: 'Artificial Necklace Set', category: 'Jewellery', gender: 'Women', price: 299, oldPrice: 699, image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=85', rating: 4.2, reviews: 61, discount: '57% OFF', description: 'Elegant imitation jewellery set that adds a festive touch to your look.' },
  { id: 8, name: 'Gold Tone Earrings', category: 'Jewellery', gender: 'Women', price: 199, oldPrice: 499, image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 83, discount: '60% OFF', description: 'Lightweight gold-tone earrings for daily wear and special occasions.' },
  { id: 9, name: "Men's Casual Shirt", category: 'Men', gender: 'Men', price: 449, oldPrice: 899, image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 130, discount: '50% OFF', description: 'Regular-fit casual shirt made for comfortable everyday styling.' },
  { id: 10, name: "Men's Sports Watch", category: 'Men', gender: 'Men', price: 799, oldPrice: 1799, image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 92, discount: '56% OFF', description: 'Sporty everyday watch with a clean dial and durable strap.' },
  { id: 11, name: 'Non-Stick Cookware Set', category: 'Kitchen', gender: 'Unisex', price: 999, oldPrice: 1999, image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 72, discount: '50% OFF', description: 'Useful non-stick cookware set for everyday home cooking.' },
  { id: 12, name: 'Stainless Steel Pan Set', category: 'Kitchen', gender: 'Unisex', price: 649, oldPrice: 1299, image: 'https://images.unsplash.com/photo-1584990347449-ae2c3b5f2b19?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 48, discount: '50% OFF', description: 'Durable stainless-steel kitchen pan set for regular cooking needs.' },
  { id: 13, name: 'Printed Cotton Kurti', category: 'Kurtis & Dresses', gender: 'Women', price: 399, oldPrice: 799, image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=800&q=85', rating: 4.6, reviews: 145, discount: '50% OFF', description: 'Breathable cotton kurti with a comfortable fit for everyday use.' },
  { id: 14, name: 'Flared Ethnic Dress', category: 'Kurtis & Dresses', gender: 'Women', price: 649, oldPrice: 1299, image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 67, discount: '50% OFF', description: 'Beautiful flared ethnic dress for festive days and family occasions.' },
  { id: 15, name: 'Kids Printed T-Shirt', category: 'Kids', gender: 'Kids', price: 249, oldPrice: 499, image: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 91, discount: '50% OFF', description: 'Soft kids T-shirt with a fun printed design and comfortable fabric.' },
  { id: 16, name: 'Kids Colourful Dress', category: 'Kids', gender: 'Kids', price: 449, oldPrice: 899, image: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 55, discount: '50% OFF', description: 'Comfortable colourful dress made for playtime and casual outings.' },
  { id: 17, name: 'Decorative Indoor Plant', category: 'Home', gender: 'Unisex', price: 299, oldPrice: 599, image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=85', rating: 4.2, reviews: 38, discount: '50% OFF', description: 'Easy-care decorative indoor plant to brighten your home or office.' },
  { id: 18, name: 'Modern Cushion Cover Set', category: 'Home', gender: 'Unisex', price: 349, oldPrice: 699, image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 64, discount: '50% OFF', description: 'Stylish cushion cover set that gives sofas and beds a fresh look.' },
  { id: 19, name: 'Matte Lipstick', category: 'Beauty', gender: 'Women', price: 299, oldPrice: 599, image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 72, discount: '50% OFF', description: 'Smooth matte-finish lipstick with a comfortable everyday feel.' },
  { id: 20, name: 'Makeup Brush Set', category: 'Beauty', gender: 'Women', price: 399, oldPrice: 799, image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=85', rating: 4.3, reviews: 58, discount: '50% OFF', description: 'Soft makeup brush set for easy and even application of beauty products.' },
  { id: 21, name: 'Running Shoes', category: 'Footwear', gender: 'Unisex', price: 1999, oldPrice: 3499, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=85', rating: 4.6, reviews: 185, discount: '43% OFF', description: 'Lightweight running shoes with cushioned comfort for daily activity.' },
  { id: 22, name: 'Women Casual Sneakers', category: 'Footwear', gender: 'Women', price: 899, oldPrice: 1799, image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 97, discount: '50% OFF', description: 'Trendy casual sneakers designed for comfortable everyday walking.' },
  { id: 23, name: 'Wireless Headphones', category: 'All Categories', gender: 'Unisex', price: 1299, oldPrice: 2499, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=85', rating: 4.4, reviews: 65, discount: '48% OFF', description: 'Wireless headphones with comfortable ear cups for music and calls.' },
  { id: 24, name: 'Smartphone', category: 'All Categories', gender: 'Unisex', price: 12999, oldPrice: 18999, image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=85', rating: 4.5, reviews: 110, discount: '32% OFF', description: 'Modern smartphone suitable for everyday communication, apps and entertainment.' },
]

const categories = [
  ['All Categories', '▦'], ['8PM Offer', '🎁'], ['Saree', '👗'], ['Western Wear', '👚'], ['Jewellery', '💎'], ['Men', '👕'], ['Kitchen', '🍳'], ['Kurtis & Dresses', '🧥'], ['Kids', '🧸'], ['Home', '🏠'], ['Beauty', '💄'], ['Footwear', '👟']
]
const money = (n: number) => `₹${n.toLocaleString('en-IN')}`

export default function App() {
  const [user, setUser] = useState<User | null>(() => JSON.parse(localStorage.getItem('apna-cart-user') || 'null'))
  const [cart, setCart] = useState<CartLine[]>(() => JSON.parse(localStorage.getItem('apna-cart-cart') || '[]'))
  const [orders, setOrders] = useState<Order[]>([])
  const [queryText, setQueryText] = useState('')
  const [category, setCategory] = useState('All')
  const [gender, setGender] = useState('All')
  const [sortBy, setSortBy] = useState('relevance')
  const [view, setView] = useState<'home' | 'cart' | 'checkout' | 'orders' | 'login'>('home')
  const [loginEmail, setLoginEmail] = useState('')
  const [otp, setOtp] = useState('')
  const [name, setName] = useState('')
  const [phone, setPhone] = useState('')
  const [address, setAddress] = useState('')
  const [email, setEmail] = useState('')
  const [payment, setPayment] = useState<PaymentMethod>('Cash on Delivery')
  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(false)

  useEffect(() => localStorage.setItem('apna-cart-cart', JSON.stringify(cart)), [cart])
  useEffect(() => { if (user) localStorage.setItem('apna-cart-user', JSON.stringify(user)); else localStorage.removeItem('apna-cart-user') }, [user])
  useEffect(() => { if (user) void loadOrders() }, [user])

  const productGender = (p: Product) => p.gender || (p.category === 'Men' || /\bmen'?s?\b/i.test(p.name) ? 'Men' : p.category === 'Kids' || /\bkids?\b/i.test(p.name) ? 'Kids' : p.category === 'All Categories' && /smartphone|headphones/i.test(p.name) ? 'Unisex' : 'Women')
  const filtered = useMemo(() => {
    const list = products.filter(p => (category === 'All' || p.category === category) && (gender === 'All' || productGender(p) === gender) && p.name.toLowerCase().includes(queryText.toLowerCase()))
    return [...list].sort((a, b) => sortBy === 'price-low' ? a.price - b.price : sortBy === 'price-high' ? b.price - a.price : sortBy === 'rating' ? b.rating - a.rating : sortBy === 'discount' ? ((b.oldPrice - b.price) / Math.max(b.oldPrice, 1)) - ((a.oldPrice - a.price) / Math.max(a.oldPrice, 1)) : 0)
  }, [category, gender, queryText, sortBy])
  const cartItems = cart.map(line => ({ ...products.find(p => p.id === line.productId)!, quantity: line.quantity })).filter(Boolean)
  const total = cartItems.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0)

  const addToCart = (id: number) => setCart(prev => prev.some(x => x.productId === id) ? prev.map(x => x.productId === id ? { ...x, quantity: x.quantity + 1 } : x) : [...prev, { productId: id, quantity: 1 }])
  const changeQty = (id: number, delta: number) => setCart(prev => prev.map(x => x.productId === id ? { ...x, quantity: x.quantity + delta } : x).filter(x => x.quantity > 0))

  async function api(path: string, options: RequestInit = {}) {
    const token = localStorage.getItem('apna-cart-token')
    const headers = new Headers(options.headers); headers.set('content-type', 'application/json'); if (token) headers.set('authorization', `Bearer ${token}`)
    const response = await fetch(`${API_BASE}${path}`, { ...options, headers }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Request failed'); return data
  }
  async function loadOrders() { try { const data = await api('/orders'); setOrders(data.orders || data || []) } catch (error) { if (error instanceof Error && /login again/i.test(error.message)) { localStorage.removeItem('apna-cart-token'); setUser(null) } } }
  async function requestOtp() { const cleanEmail = loginEmail.trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(cleanEmail)) return setMessage('Valid email address dijiye.'); if (!name.trim()) return setMessage('Name dijiye.'); setLoading(true); setMessage(''); try { await api('/auth/request-otp', { method: 'POST', body: JSON.stringify({ name: name.trim(), contact: cleanEmail }) }); setMessage('OTP aapke email par bhej diya gaya. Email check karein.') } catch (error) { setMessage(error instanceof Error ? error.message : 'OTP send nahi hua.') } setLoading(false) }
  async function verifyOtp() { const cleanEmail = loginEmail.trim().toLowerCase(); if (!otp.trim()) return setMessage('OTP enter karein.'); setLoading(true); setMessage(''); try { const data = await api('/auth/verify-otp', { method: 'POST', body: JSON.stringify({ contact: cleanEmail, otp }) }); if (!data.token) throw new Error('Login token nahi mila.'); localStorage.setItem('apna-cart-token', data.token); const loggedUser = data.user || { name: name.trim() || 'Apna Cart User', contact: cleanEmail }; setUser(loggedUser); setLoginEmail(loggedUser.contact); setView('home'); setMessage('Login successful!') } catch (error) { setMessage(error instanceof Error ? error.message : 'OTP verify nahi hua.') } setLoading(false) }
  async function placeOrder() { if (!user) return setView('login'); if (!address.trim() || phone.replace(/\D/g, '').length < 10) return setMessage('Address aur valid mobile number bhariye.'); setLoading(true); setMessage(''); try { const data = await api('/orders', { method: 'POST', body: JSON.stringify({ customer: user, items: cartItems, total, address, phone, email, paymentMethod: payment }) }); setOrders(prev => [data.order, ...prev]); setCart([]); setView('orders'); setMessage('Order place ho gaya!') } catch (error) { setMessage(error instanceof Error ? error.message : 'Order place nahi hua.') } setLoading(false) }
  async function updateStatus(order: Order, status: string) { const location = status === 'Processing' ? 'Order received' : status === 'Accepted' ? 'Order accepted' : status === 'Shipped' ? 'On the way' : 'Delivered'; try { const data = await api(`/orders/${order.id}/status`, { method: 'PATCH', body: JSON.stringify({ status, location }) }); setOrders(prev => prev.map(x => x.id === order.id ? (data.order || { ...x, status, location }) : x)) } catch (error) { setMessage(error instanceof Error ? error.message : 'Status update nahi hua.') } }
  function logout() { localStorage.removeItem('apna-cart-token'); setUser(null); setOrders([]); setView('home'); setMessage('Logout successful.') }
  const goHome = () => { setView('home'); window.scrollTo({ top: 0, behavior: 'smooth' }) }

  return <div className="app-shell">
    <header className="top-header">
      <div className="header-topline"><button className="refer-pill" onClick={() => setMessage('Refer & Earn feature coming soon.')}>🎁 Refer and Earn</button><span className="wallet">₹0 <b>▣</b></span><button className="header-icon" onClick={() => setMessage('Wishlist feature coming soon.')} aria-label="Wishlist">♡</button><button className="header-icon cart-head" onClick={() => setView('cart')} aria-label="Cart">🛒<i>{cartCount}</i></button></div>
      <button className="brand" onClick={goHome}><span className="brand-mark">🛒</span><span><b>Apna Cart</b><small>Har Ghar Ki Zarurat</small></span></button>
    </header>
    <main className="main-content">
      <div className="search-box"><span>⌕</span><input value={queryText} onChange={e => setQueryText(e.target.value)} placeholder="Search by Keyword or Product ID" /><button onClick={() => setMessage('Voice search coming soon.')} aria-label="Voice search">🎙</button><button onClick={() => setMessage('Camera search coming soon.')} aria-label="Camera search">▣</button></div>
      {message && <div className="message">{message}</div>}
      {view === 'home' && <>
        <section className="hero-banner"><div><span>APNA CART SPECIAL</span><h1>Best Quality<br /><b>Lowest Prices</b></h1><p>Fashion&nbsp; | &nbsp;Home&nbsp; | &nbsp;Beauty&nbsp; | &nbsp;More</p><button onClick={() => { setCategory('All'); setGender('All'); setSortBy('relevance'); setQueryText('') }}>Shop Now →</button></div><div className="hero-art">🛍️</div><div className="hero-dots">● ○ ○ ○</div></section>
        <section className="category-strip">{categories.map(([label, icon]) => <button key={label} className={`category-item ${label === 'All Categories' ? category === 'All' ? 'active' : '' : category === label ? 'active' : ''}`} onClick={() => setCategory(label === 'All Categories' ? 'All' : label)}><span className="category-icon">{icon}</span><span>{label}</span></button>)}</section>
        <section className="filter-row">
          <select aria-label="Sort products" value={sortBy} onChange={e => setSortBy(e.target.value)}><option value="relevance">↕ Sort</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option><option value="rating">Top Rated</option><option value="discount">Best Discount</option></select>
          <select aria-label="Category" value={category} onChange={e => setCategory(e.target.value)}><option value="All">Category</option>{categories.map(([label]) => label !== 'All Categories' && <option key={label} value={label}>{label}</option>)}</select>
          <select aria-label="Gender" value={gender} onChange={e => setGender(e.target.value)}><option value="All">Gender</option><option value="Women">Women</option><option value="Men">Men</option><option value="Kids">Kids</option><option value="Unisex">Unisex</option></select>
          <select aria-label="Filters" value="all" onChange={e => { if (e.target.value === 'reset') { setCategory('All'); setGender('All'); setSortBy('relevance'); setQueryText('') } }}><option value="all">≡ Filters</option><option value="reset">Reset All Filters</option></select>
        </section>
        <section className="section-heading"><h2>{category === 'All' ? 'Trending For You' : category}</h2><button onClick={() => { setCategory('All'); setGender('All'); setSortBy('relevance'); setQueryText('') }}>View All →</button></section>
        <section className="product-grid">{filtered.map((p, index) => <article key={p.id} className="product-card"><div className="product-image-wrap"><span className="product-tag">{index % 3 === 0 ? 'Best Seller' : index % 3 === 1 ? 'Top Rated' : 'Trending'}</span><button className="heart" onClick={() => setMessage('Wishlist feature coming soon.')} aria-label="Wishlist">♡</button><img src={p.image} alt={p.name} /></div><div className="product-info"><h3>{p.name}</h3><p className="product-description">{p.description}</p><div className="price-row"><strong>{money(p.price)}</strong><del>{money(p.oldPrice)}</del><span className="discount">{p.discount}</span></div><div className="cod">{money(Math.round(p.price * 1.1))} with COD</div><div className="rating"><b>★ {p.rating}</b> <span>({p.reviews.toLocaleString('en-IN')})</span></div><button className="add-button" onClick={() => { addToCart(p.id); setMessage(`${p.name} cart me add ho gaya.`) }}>🛒 Add to Cart</button></div></article>)}</section>
      </>}
      {view === 'cart' && <section className="page-card"><h2>🛒 Your Cart</h2>{cartItems.length === 0 ? <p>Cart empty hai.</p> : <>{cartItems.map(item => <div className="cart-line" key={item.id}><img src={item.image} alt="" /><div className="cart-detail"><b>{item.name}</b><span>{money(item.price)}</span><div className="qty"><button onClick={() => changeQty(item.id, -1)}>-</button><b>{item.quantity}</b><button onClick={() => changeQty(item.id, 1)}>+</button></div></div></div>)}<div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary-wide" onClick={() => user ? setView('checkout') : setView('login')}>Proceed to Checkout</button></>}</section>}
      {view === 'login' && <section className="form-card"><h2>Login / Register</h2><p className="muted">Apna Cart par shopping shuru karein.</p><input value={name} onChange={e => setName(e.target.value)} placeholder="Full name" /><input type="email" value={loginEmail} onChange={e => setLoginEmail(e.target.value)} placeholder="Email address" autoComplete="email" /><button className="primary-wide" disabled={loading} onClick={requestOtp}>{loading ? 'Sending...' : 'Send OTP'}</button><input inputMode="numeric" value={otp} onChange={e => setOtp(e.target.value)} placeholder="Enter OTP" maxLength={6} /><button className="primary-wide" disabled={loading} onClick={verifyOtp}>{loading ? 'Verifying...' : 'Verify & Login'}</button><p className="muted small">Free option: OTP email par aayega. Firebase SMS billing ki zarurat nahi hai.</p></section>}
      {view === 'checkout' && <section className="form-card"><h2>📦 Checkout</h2><textarea value={address} onChange={e => setAddress(e.target.value)} placeholder="Full delivery address" rows={4} /><input value={phone} onChange={e => setPhone(e.target.value)} placeholder="Mobile number" /><input value={email} onChange={e => setEmail(e.target.value)} placeholder="Email (optional)" /><label>Payment method</label><select value={payment} onChange={e => setPayment(e.target.value as PaymentMethod)}>{(['UPI', 'Card', 'Net banking', 'Wallet', 'Cash on Delivery'] as PaymentMethod[]).map(x => <option key={x}>{x}</option>)}</select><div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary-wide" disabled={loading} onClick={placeOrder}>{loading ? 'Placing...' : 'Place Order'}</button></section>}
      {view === 'orders' && <section className="page-card"><h2>📦 My Orders</h2>{orders.length === 0 ? <p>No orders yet.</p> : orders.map(order => <article className="order-card" key={order.id}><div className="order-head"><b>Order #{String(order.id).slice(0, 8)}</b><strong>{money(order.total)}</strong></div><p>📍 {order.location || order.address}</p><p>Status: <b>{order.status}</b></p><div className="status-row">{['Processing', 'Accepted', 'Shipped', 'Delivered'].map(s => <button key={s} className={order.status === s ? 'selected' : ''} onClick={() => updateStatus(order, s)}>{s}</button>)}</div></article>)}</section>}
    </main>
    <nav className="bottom-nav"><button className={view === 'home' ? 'active' : ''} onClick={goHome}><span>⌂</span>Home</button><button className="nav-category" onClick={() => { setView('home'); setCategory('All'); setGender('All') }}><span>▦</span>Categories</button><button className={view === 'cart' ? 'active' : ''} onClick={() => setView('cart')}><span>🛒<i>{cartCount}</i></span>Cart</button><button onClick={() => setMessage('Wishlist feature coming soon.')}><span>♡</span>Wishlist</button><button className={view === 'login' || user ? 'active' : ''} onClick={() => user ? logout() : setView('login')}><span>♙</span>{user ? 'Logout' : 'Account'}</button></nav>
  </div>
}
